### ISSUE TITLE
How You can Help webform on bridgefoundry.org needs to be updated.

### ISSUE THREAD

**Issue by jeneenp** [bridgefoundry/bridgefoundry.github.io#110] opened 2018-09-13 15:50 UTC
A New Google form was created in the Team Drive to capture the responses. Here is the link to the new form: https://drive.google.com/open?id=1rbTlwPGzoICMUzQIZHVQX3nc77KQXGJcBRDms9R3g24

**Comment by iisa** [comment] 2019-06-09 15:10
@jeneenp please can you ensure that this form can be open by the public? it looked like I had to request access

**Comment by iisa** [comment] 2019-06-09 15:59
@jeneenp also please confirm if the issue #104 is old, a duplicate of this

**Comment by jeneenp** [comment] 2019-06-10 14:12
When Diana left, she did not transfer the form to Bridge Foundry for
ownership. I had to create a new form. Issue 104 should be closed. Issue
110 is valid. I changed the settings on the form. My apologies.

Thanks in advance,

Jéneen R. Perkins
Finance Manager

Bridge Foundry
340 S. Lemon Avenue #3994N
Walnut, CA 91789
916-776-6448

**Closed** 2019-08-18 00:37 UTC
Labels: question
